import { combineReducers } from "redux";
import { user, matches, connections, checkinCode, currentMatch } from "./reducers";

export default combineReducers({
  user,
  matches,
  connections,
  progess: () => null,
  currentMatch,
  // selectedConnection: () => {},
  checkinCode,
  skills: () => [
    "Accounting",
    "Training",
    "Legal",
    "Digital Media",
    "Consulting",
    "Marketing",
    "Photography",
    "Videography",
    "Architecture",
    "Chef/Catering",
    "Hospitality",
    "Software development",
    "Technician",
    "Content Creation",
    "Social Media",
    "Team Building",
    "Leadership",
    "Design Thinking",
    "Administrative",
    "Customer Success",
  ],
  interests: () => [
    "Entrepreneurship",
    "Marketing",
    "Business",
    "Social Media",
    "Design",
    "Websites",
    "Networking",
    "Coaching",
    "Technology",
    "Travel",
    "Teamwork",
    "Volunteers",
    "Graphics",
    "Photography",
    "Collaboration",
    "Food",
    "Investment",
    "Real Estate",
    "Marine",
    "Sustainability",
    "Shared Economy",
    "Online Business",
    "Fintech",
    "Global Business",
    "Taxes"
  ]
});